"""
    AggregateIO

Read aggregate geometry files generated by aggregate_generator_PTSA.

Expected file format:
- Text file, one monomer per line
- Each line: x y z r (position and radius, whitespace-separated)
- Coordinates may be dimensionless (normalized by monomer radius) or physical
"""

export read_aggregate_file, AggregateGeometry

"""
    AggregateGeometry

Container for aggregate particle geometry data.

# Fields
- `positions::Matrix{Float64}`: Monomer center positions [3 × N_monomers]
- `radii::Vector{Float64}`: Monomer radii [N_monomers]
- `n_monomers::Int`: Number of monomers
- `filename::String`: Source file path
"""
struct AggregateGeometry
    positions::Matrix{Float64}  # [3, N]
    radii::Vector{Float64}      # [N]
    n_monomers::Int
    filename::String
end

"""
    read_aggregate_file(filepath::String; scale_factor::Float64=1.0) -> AggregateGeometry

Read an aggregate geometry file from aggregate_generator_PTSA.

# Arguments
- `filepath`: Path to the aggregate geometry text file
- `scale_factor`: Multiply all positions and radii by this factor.
                  Use this to convert from dimensionless to physical units
                  (e.g., scale_factor = monomer_radius_in_meters).

# File format
Each line contains: `x y z r` (whitespace-separated floats)
Lines starting with `#` are treated as comments and skipped.
Empty lines are skipped.
"""
function read_aggregate_file(filepath::String; scale_factor::Float64 = 1.0)::AggregateGeometry
    positions_list = Vector{Float64}[]
    radii_list = Float64[]

    open(filepath, "r") do io
        for line in eachline(io)
            stripped = strip(line)
            # Skip comments and empty lines
            if isempty(stripped) || startswith(stripped, "#")
                continue
            end
            parts = split(stripped)
            if length(parts) >= 4
                x = parse(Float64, parts[1]) * scale_factor
                y = parse(Float64, parts[2]) * scale_factor
                z = parse(Float64, parts[3]) * scale_factor
                r = parse(Float64, parts[4]) * scale_factor
                push!(positions_list, [x, y, z])
                push!(radii_list, r)
            end
        end
    end

    n = length(radii_list)
    positions = hcat(positions_list...)  # [3, N]

    return AggregateGeometry(positions, radii_list, n, filepath)
end
