"""
    AggregateIO

Read aggregate geometry data from:
- Text files (.ptsa, .pos) generated by aggregate_generator_PTSA
- HDF5 + CSV catalog produced by aggregate_generator_PTSA batch mode

Expected .ptsa/.pos format:
- One monomer per line, 4 whitespace-separated columns: x y z r
- No header; coordinates and radii in μm

HDF5 + CSV catalog format (aggregate_generator_PTSA):
- CSV: columns mean_rp, rel_std_rp, k, Df, Np, agg_num, Rve, Rg, eps_agg, h5_file, h5_key
- HDF5: groups at h5_key path, each containing datasets `xp` (3×Np) and `rp` (Np)
"""

export read_aggregate_file, read_aggregate_catalog, AggregateGeometry

using CSV, DataFrames, HDF5

"""
    AggregateGeometry

Container for aggregate particle geometry data and associated metadata.

# Fields — geometry
- `positions::Matrix{Float64}`: Monomer center positions [3 × N_monomers] in μm
- `radii::Vector{Float64}`: Monomer radii [N_monomers] in μm
- `n_monomers::Int`: Number of monomers

# Fields — metadata (from catalog; NaN/0/"" if unavailable)
- `source::String`: Source identifier (file path or h5_key)
- `Df::Float64`: Fractal dimension
- `k_f::Float64`: Fractal prefactor (NOT wavenumber)
- `mean_rp::Float64`: Mean monomer radius [μm]
- `rel_std_rp::Float64`: Relative std dev of monomer radius
- `agg_num::Int`: Aggregate index within the (Df, Np, k_f) group
- `R_ve::Float64`: Volume-equivalent sphere radius [μm]
- `R_g::Float64`: Radius of gyration [μm]
- `eps_agg::Float64`: Aggregate porosity
"""
struct AggregateGeometry
    positions::Matrix{Float64}   # [3, N]
    radii::Vector{Float64}       # [N]
    n_monomers::Int
    source::String
    # Metadata — fractal / morphological parameters
    Df::Float64
    k_f::Float64
    mean_rp::Float64
    rel_std_rp::Float64
    agg_num::Int
    R_ve::Float64
    R_g::Float64
    eps_agg::Float64
end

# Convenience constructor for backward compatibility (no metadata)
function AggregateGeometry(positions::Matrix{Float64}, radii::Vector{Float64},
                           n_monomers::Int, source::String)
    R_ve = cbrt(sum(r^3 for r in radii))
    AggregateGeometry(positions, radii, n_monomers, source,
                      NaN, NaN, NaN, NaN, -1, R_ve, NaN, NaN)
end

"""
    read_aggregate_file(filepath::String; scale_factor::Float64=1.0) -> AggregateGeometry

Read an aggregate geometry from a .ptsa or .pos text file.

# Arguments
- `filepath`: Path to the aggregate geometry text file
- `scale_factor`: Multiply all positions and radii by this factor (default 1.0)

# File format
Each line: `x y z r` (whitespace-separated). Lines starting with `#` are skipped.
"""
function read_aggregate_file(filepath::String; scale_factor::Float64 = 1.0)::AggregateGeometry
    positions_list = Vector{Float64}[]
    radii_list = Float64[]

    open(filepath, "r") do io
        for line in eachline(io)
            stripped = strip(line)
            if isempty(stripped) || startswith(stripped, "#")
                continue
            end
            parts = split(stripped)
            if length(parts) >= 4
                x = parse(Float64, parts[1]) * scale_factor
                y = parse(Float64, parts[2]) * scale_factor
                z = parse(Float64, parts[3]) * scale_factor
                r = parse(Float64, parts[4]) * scale_factor
                push!(positions_list, [x, y, z])
                push!(radii_list, r)
            end
        end
    end

    n = length(radii_list)
    positions = hcat(positions_list...)  # [3, N]

    # Try to parse metadata from PTSA filename
    bn = basename(filepath)
    meta = _parse_ptsa_filename(bn)
    R_ve = cbrt(sum(r^3 for r in radii_list))

    return AggregateGeometry(
        positions, radii_list, n, filepath,
        meta.Df, meta.k_f, meta.mean_rp, meta.rel_std_rp,
        meta.agg_num, R_ve, NaN, NaN
    )
end

"""
    _parse_ptsa_filename(basename) -> NamedTuple

Extract metadata from PTSA filename convention:
  `meanRp={val}um_rstdRp={val}_k={val}_Df={val}_Np={val}_agg_num={val}.ptsa`

Returns NaN/-1 for fields that cannot be parsed.
"""
function _parse_ptsa_filename(bn::String)
    function _extract(pattern, s, T=Float64)
        m = match(pattern, s)
        m === nothing && return (T == Int ? -1 : NaN)
        return parse(T, m[1])
    end
    mean_rp    = _extract(r"meanRp=([\d.eE+-]+)um", bn)
    rel_std_rp = _extract(r"rstdRp=([\d.eE+-]+)", bn)
    k_f        = _extract(r"(?:^|_)k=([\d.eE+-]+)", bn)
    Df         = _extract(r"Df=([\d.eE+-]+)", bn)
    agg_num    = _extract(r"agg_num=(\d+)", bn, Int)
    return (mean_rp=mean_rp, rel_std_rp=rel_std_rp, k_f=k_f, Df=Df, agg_num=agg_num)
end

"""
    read_aggregate_catalog(h5_file::String, csv_file::String;
                           Df_range=nothing, Np_range=nothing,
                           agg_num_range=nothing) -> Vector{AggregateGeometry}

Read aggregates from an HDF5 + CSV catalog produced by aggregate_generator_PTSA.

# Arguments
- `h5_file`: Path to the HDF5 file containing monomer coordinates
- `csv_file`: Path to the CSV catalog file
- `Df_range`: Optional `(min, max)` tuple to filter by fractal dimension
- `Np_range`: Optional `(min, max)` tuple to filter by number of monomers
- `agg_num_range`: Optional `(min, max)` tuple to filter by aggregate index

# Returns
Vector of `AggregateGeometry` with full metadata populated from the catalog.
Coordinates are in the original units (μm) as stored in the HDF5 file.
"""
function read_aggregate_catalog(
    h5_file::String,
    csv_file::String;
    Df_range::Union{Nothing, Tuple{Float64,Float64}} = nothing,
    Np_range::Union{Nothing, Tuple{Int,Int}} = nothing,
    agg_num_range::Union{Nothing, Tuple{Int,Int}} = nothing
)::Vector{AggregateGeometry}

    catalog = CSV.read(csv_file, DataFrame)

    # ── Apply filters ──────────────────────────────────────────────────────
    if Df_range !== nothing
        catalog = filter(row -> Df_range[1] <= row.Df <= Df_range[2], catalog)
    end
    if Np_range !== nothing
        catalog = filter(row -> Np_range[1] <= row.Np <= Np_range[2], catalog)
    end
    if agg_num_range !== nothing
        catalog = filter(row -> agg_num_range[1] <= row.agg_num <= agg_num_range[2], catalog)
    end

    n_agg = nrow(catalog)
    aggregates = Vector{AggregateGeometry}(undef, n_agg)

    h5dir = dirname(h5_file)

    HDF5.h5open(h5_file, "r") do fid
        for i in 1:n_agg
            row = catalog[i, :]

            # Read geometry from HDF5
            g = fid[row.h5_key]
            xp = read(g["xp"])   # (3, Np) Float64
            rp = read(g["rp"])   # (Np,) Float64

            Np = length(rp)
            # xp may be (3, Np) or (Np, 3) depending on h5py write order
            if size(xp, 1) == 3 && size(xp, 2) == Np
                positions = xp
            elseif size(xp, 1) == Np && size(xp, 2) == 3
                positions = Matrix{Float64}(xp')
            else
                error("Unexpected xp shape $(size(xp)) for h5_key=$(row.h5_key)")
            end

            aggregates[i] = AggregateGeometry(
                positions, rp, Np, row.h5_key,
                Float64(row.Df),
                Float64(row.k),
                Float64(row.mean_rp),
                Float64(row.rel_std_rp),
                Int(row.agg_num),
                Float64(row.Rve),
                Float64(row.Rg),
                Float64(row.eps_agg),
            )
        end
    end

    return aggregates
end
